=== DOOM097/XML-TEST/country.dtd
<!ELEMENT root (currencys)>
<!ELEMENT currencys (currency+)>
<!ELEMENT currency (country,year)>
<!ATTLIST currency title ID #REQUIRED>
<!ELEMENT country (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== DOOM097/XML-TEST/country.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "country.dtd">
<root>
    <currencys>
        <currency title="Euro"> 
            <country>Estonia</country>
            <year>2011</year>
        </currency>

        <currency title="Dollars"> 
            <country>USA</country>
            <year>1785</year>
        </currency>

        <currency title="Real"> 
            <country>Brasil</country>
            <year>1994</year>
        </currency>
    
        <currency title="Rubles"> 
            <country>Russia</country>
            <year>1991</year>
        </currency>

        <currency title="Peso"> 
            <country>Argentina</country>
            <year>1992</year>
        </currency>
        
        <currency title="Yen"> 
            <country>Japan</country>
            <year>1869</year>
        </currency>

        <currency title="Renminbi"> 
            <country>China</country>
            <year>1948</year>
        </currency>

        <currency title="Lari"> 
            <country>Grusia</country>
            <year>1995</year>
        </currency>

        <currency title="Rupia"> 
            <country>India</country>
            <year>1917</year>
        </currency>

        <currency title="Rial"> 
            <country>Iran</country>
            <year>1798</year>
        </currency>
    </currencys>
</root>
